In [78]:
import pandas as pd
import numpy as np

In [4]:
players = pd.read_csv('Seasons_Stats.csv')

In [18]:
df = players.groupby(['Year','Player']).sum().groupby('Player').cumsum()

In [22]:
df = df.reset_index()
df

,Year,Player,Unnamed: 0,Age,G,GS,MP,PER,TS%,3PAr,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Al Cervi*,32,32.0,56.0,0.0,0.0,0.0,0.491,0.000,...,0.829,0.0,0.0,0.0,264.0,0.0,0.0,0.0,223.0,573.0
1,1950.0,Al Guokas,258,72.0,114.0,0.0,0.0,0.0,0.961,0.000,...,2.092,0.0,0.0,0.0,190.0,0.0,0.0,0.0,286.0,428.0
2,1950.0,Al Miksis,174,21.0,8.0,0.0,0.0,0.0,0.446,0.000,...,0.810,0.0,0.0,0.0,4.0,0.0,0.0,0.0,22.0,27.0
3,1950.0,Alex Groza,84,23.0,64.0,0.0,0.0,0.0,0.548,0.000,...,0.729,0.0,0.0,0.0,162.0,0.0,0.0,0.0,221.0,1496.0
4,1950.0,Alex Hannum*,92,26.0,64.0,0.0,0.0,0.0,0.423,0.000,...,0.688,0.0,0.0,0.0,129.0,0.0,0.0,0.0,264.0,482.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20281,2017.0,Wilson Chandler,232729,263.0,588.0,425.0,18431.0,146.3,5.714,3.255,...,8.507,680.0,2543.0,3223.0,1045.0,435.0,436.0,863.0,1648.0,8315.0
20282,2017.0,Yogi Ferrell,72780,69.0,92.0,58.0,2394.0,33.7,1.556,1.430,...,2.333,40.0,182.0,222.0,344.0,84.0,18.0,140.0,180.0,924.0
20283,2017.0,Zach LaVine,71439,60.0,206.0,120.0,5945.0,40.2,1.639,1.014,...,2.471,72.0,529.0,601.0,666.0,164.0,37.0,433.0,455.0,2817.0
20284,2017.0,Zach Randolph,361447,494.0,1107.0,870.0,34865.0,345.9,9.350,0.815,...,13.541,3339.0,6976.0,10315.0,2025.0,835.0,307.0,2288.0,2643.0,18762.0
20285,2017.0,Zaza Pachulia,289198,357.0,961.0,456.0,20390.0,196.6,7.494,0.079,...,10.408,2174.0,3555.0,5729.0,1233.0,699.0,344.0,1316.0,2465.0,6774.0

In [24]:
sub = df[['Year','Player','PTS']]

In [25]:
sub

         Year           Player      PTS
0      1950.0        Al Cervi*    573.0
1      1950.0        Al Guokas    428.0
2      1950.0        Al Miksis     27.0
3      1950.0       Alex Groza   1496.0
4      1950.0     Alex Hannum*    482.0
...       ...              ...      ...
20281  2017.0  Wilson Chandler   8315.0
20282  2017.0     Yogi Ferrell    924.0
20283  2017.0      Zach LaVine   2817.0
20284  2017.0    Zach Randolph  18762.0
20285  2017.0    Zaza Pachulia   6774.0

[20286 rows x 3 columns]

In [30]:
sub.pivot_table(values='PTS', index=sub.Player, columns='Year')

Year,1950.0,1951.0,1952.0,1953.0,1954.0,1955.0,1956.0,1957.0,1958.0,1959.0,...,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0
Player,,,,,,,,,,,,,,,,,,,,,
A.C. Green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.J. Bramlett,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.J. English,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.J. Guyton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.J. Hammons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zelmo Beaty*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zendon Hamilton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoran Dragic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,NaN,NaN
Zoran Planinic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zydrunas Ilgauskas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9304.0,10142.0,10616.0,10976.0,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
test =  sub.reset_index().groupby(['Player', 'Year'])['PTS'].aggregate('first').unstack()

In [36]:
test = test.fillna(axis=1, method='ffill')

In [37]:
test = test.fillna(0)

In [42]:
test.to_csv('done.csv')

In [50]:
test.loc['LeBron James']

Year
1950.0        0.0
1951.0        0.0
1952.0        0.0
1953.0        0.0
1954.0        0.0
           ...
2013.0    21081.0
2014.0    23170.0
2015.0    24913.0
2016.0    26833.0
2017.0    28787.0
Name: LeBron James, Length: 68, dtype: float64

In [83]:
test['2018'] = np.nan

In [84]:
test = test.fillna(axis=1, method='ffill')

In [85]:
test['2018']['LeBron James'] = 31596

In [86]:
test['2019'] = np.nan

In [60]:
2251+28787

31038

In [61]:
33101

33101

In [87]:
test = test.fillna(axis=1,method='ffill')

In [88]:
test['2019']['LeBron James'] = 33101

In [90]:
test.to_csv('done.csv')

In [ ]:
https://www.pngfind.com/pngs/m/470-4701678_michael-jordan-transparent-black-and-white-png-download.png
https://www.pngarts.com/files/5/LeBron-James-PNG-Photo.png

In [91]:
test

Year,1950.0,1951.0,1952.0,1953.0,1954.0,1955.0,1956.0,1957.0,1958.0,1959.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018,2019
Player,,,,,,,,,,,,,,,,,,,,,
A.C. Green,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12928.0,12928.0,12928.0,12928.0,12928.0,12928.0,12928.0,12928.0,12928.0,12928.0
A.J. Bramlett,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
A.J. English,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1502.0,1502.0,1502.0,1502.0,1502.0,1502.0,1502.0,1502.0,1502.0,1502.0
A.J. Guyton,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,442.0,442.0,442.0,442.0,442.0,442.0,442.0,442.0,442.0,442.0
A.J. Hammons,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,48.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zelmo Beaty*,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9107.0,9107.0,9107.0,9107.0,9107.0,9107.0,9107.0,9107.0,9107.0,9107.0
Zendon Hamilton,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,611.0,611.0,611.0,611.0,611.0,611.0,611.0,611.0,611.0,611.0
Zoran Dragic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,56.0,56.0,56.0,56.0,56.0
Zoran Planinic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,561.0,561.0,561.0,561.0,561.0,561.0,561.0,561.0,561.0,561.0
Zydrunas Ilgauskas,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10616.0,10976.0,10976.0,10976.0,10976.0,10976.0,10976.0,10976.0,10976.0,10976.0